plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'io.github.fredoseep.bilidanmucheck'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "io.github.fredoseep.bilidanmucheck"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildFeatures {
        buildConfig = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    packaging {
        jniLibs {
            useLegacyPackaging false
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation(libs.dexkit.v220)
    compileOnly libs.api
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}